### ISSUE TITLE
Ftarget fails to generate when fuzzing Nginx

### ISSUE THREAD

**Issue by cty12** [aflgo/aflgo#1]
### Fuzzing target
[Nginx server](http://nginx.org/en/security_advisories.html)
### Patch used
The [patch](http://nginx.org/download/patch.2017.ranges.txt) for [CVE-2017-7529](http://mailman.nginx.org/pipermail/nginx-announce/2017/000200.html?_ga=2.60495405.1855881314.1504632682-1196777374.1504293460). 
The [patch](http://nginx.org/download/patch.2016.write.txt) for [CVE-2016-4450](http://mailman.nginx.org/pipermail/nginx-announce/2016/000179.html?_ga=2.60338605.1855881314.1504632682-1196777374.1504293460). 
### Nginx version
nginx-1.12.1 (latest stable release as of Sept. 5, 2017)
Download release tarball [here](http://nginx.org/download/nginx-1.12.1.tar.gz). 
### Aflgo version
Compiled from latest commit on master branch.
### Issue description
`$TMP_DIR/Ftargets.txt` is empty (i.e no content) after compiling. Take CVE-2016-4450 for an example, we write `$TMP_DIR/BBtargets.txt` manually (instead of generating from git commit), which is:
```
src/os/unix/ngx_files.c:360
src/os/unix/ngx_files.c:361
src/os/unix/ngx_files.c:362
```
### Minor comment
Note that we have to disable *linker optimization* (compiler option -flto) to get Nginx to compile using `afl-clang-fast` and (other) CFLAGS required by Aflgo.

**Comment by aflgo** [comment]
Thanks for your issue report!

The problem here is that disabling the compiler option -flto will disable the GOLD plugin for LLVM (http://llvm.org/docs/GoldPlugin.html). This in turn will disable some functionality in afl-llvm-pass.so.cc.

During compilation,
* If the linker (CCLD) complains that you should run ranlib, make sure that libLTO.so and LLVMgold.so (from building LLVM with Gold) can be found in /usr/lib/bfd-plugins
* If the compiler crashes, there is some problem with LLVM not supporting our instrumentation (afl-llvm-pass.so.cc:540-577). LLVM has changed the instrumentation-API very often :(
 -> Check LLVM-version, fix problem, and prepare pull request.

If you have problems setting up the most recent version of LLVM with GOLD, we suggest to build and use the Docker image which is available at: https://github.com/aflgo/oss-fuzz/blob/master/infra/base-images/base-clang/.

**Comment by cty12** [comment]
Thank you for your reply. 

However Nginx does not compile with `-flto`. It reports that the format of `nginx.o` cannot be recognized during linking.

**Comment by CoupleFuzz** [comment]
> Thank you for your reply.
> 
> However Nginx does not compile with `-flto`. It reports that the format of `nginx.o` cannot be recognized during linking.

I also encountered this quesiton, when I fuzz project vim by aflgo
this is mys cripts:
```shell
#!/bin/bash
git clone git@github.com:vim/vim.git vim_b2209f21
cd vim_b2209f21
git reset  b2209f213e2931cf3313b24868a9165bbb717cc4
mkdir obj-aflgo; mkdir obj-aflgo/temp
export SUBJECT=$PWD; export TMP_DIR=$PWD/obj-aflgo/temp
export CC=$AFLGO/instrument/aflgo-clang; export CXX=$AFLGO/instrument/aflgo-clang++
export LDFLAGS=-lpthread
export ADDITIONAL="-targets=$TMP_DIR/BBtargets.txt -outdir=$TMP_DIR -flto -fuse-ld=gold -Wl,-plugin-opt=save-temps"
# my method to generate BBtargets
python3 /aflgo/tools/DiffMethodSearch.py > obj-aflgo/temp/BBtargets.txt
make distclean
cd src
CFLAGS="$ADDITIONAL" CXXFLAGS="$ADDITIONAL" ./configure --with-features=huge --enable-gui=no --enable-pythoninterp=no --disable-shared 
make clean; make
```
error:
```
aflgo-compiler (yeah!) 2.57b
objects/alloc.o: file not recognized: file format not recognized
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
link.sh: Linking failed
make: *** [Makefile:2061: vim] Error 1
```
but if I copile with `export ADDITIONAL="-targets=$TMP_DIR/BBtargets.txt -outdir=$TMP_DIR "` dont use ` -flto -fuse-ld=gold -Wl ` I could susscesss compile, but I cant generate distance graph. This is my problem
![ced1531f15c896e7293feb5aac51f40](https://github.com/user-attachments/assets/802338e8-0199-43f6-bf56-b573c1b56054)
