### ISSUE TITLE
Ftarget.txt is incorrect

### ISSUE THREAD

**Issue by legend-issue** [aflgo/aflgo#11]
When I use libtiff to have a try,I set location manually and as the rule.But I found the Ftarget.txt is incorrect,because I choose an alone function,but it's always main.I don't know why.

**Comment by mboehme** [comment]
The problem is that AFLGo's LLVM-pass cannot identify the basic block corresponding to the specified program location (and therefore the function containing that basic block). This can have two reasons:
1) the format how you specify the target is incorrect (e.g., "file.c:123" would be correct)
2) LLVM may not carry line number information for all instructions.
LLVM encodes the location (file / line number) corresponding to an instruction in a basic block. We access the location information of an instruction via getDebugLoc (https://github.com/aflgo/aflgo/blob/master/llvm_mode/afl-llvm-pass.so.cc#L288). It seems not all instruction carry such debug information.
