### ISSUE TITLE
Why not implement the standard harmonic mean distance calculation as paper said?

### ISSUE THREAD

**Issue by daydayup40** [aflgo/aflgo#39]
I read the code, and see that the distance calculation is not standard harmonic mean distance.
As below, the distance will update only if distance > i / d, this will introduce some difference when test with the example in figure 4 in your paper. By this mean, the distances for 3 node in the figure will be 2, 3, 8/3. While the harmonic mean distances for 3 node in the figure are 3/4, 1, 3/4.
1) Why did you choose this means?
2) Is there any problem?
if d != 0 and (distance == -1 or distance > i / d) :
      distance = i / d
https://github.com/aflgo/aflgo/blob/d98ad6519717a9f339d2bad5bd2164107afe7297/scripts/distance.py#L55

**Comment by LockOne** [comment]
The paper says AFLGo is using harmonic mean distance which is
![image](https://user-images.githubusercontent.com/20575207/53150672-5d974d80-35f4-11e9-8119-f8511afc786f.png)
But, actually implementation shows
![image](https://user-images.githubusercontent.com/20575207/53150688-70aa1d80-35f4-11e9-80e9-3c064f98646c.png)

The multiplied number of reachable target functions to increase distance for caller functions.
It makes sense since the caller function would be 'further' from the target location than the callee function, but I think they should mention them since it will affect directing...

**Comment by bjchan9an** [comment]
In Figure4 the harmonic mean is calculated as  1/(1/2 + 1/2)， but it should be like:
![tiaohe](https://user-images.githubusercontent.com/36298629/67613819-793a9f80-f7e4-11e9-89f5-76d5c101add7.png)
The implementation in code is right （the "n" in numerator）.

Something else in code which is a bit different from the paper, "+1" was added to denominator, maybe is to avoid the div 0.

And the final basic blocks's distance is  the average of each situation, instead of  considering in different situations as Formula 2 in paper. I guess this is to take more situations into consideration, instead of merely the shortest distance.

The line you pointed is to calculate the mininum distance, as there may be several nodes returned from ``find_nodes()``.(not sure)
