### ISSUE TITLE
How to instrument with afl-gcc?

### ISSUE THREAD

**Issue by Hack-Me** [aflgo/aflgo#63]
when i want to instrument elfutils(libelf), i found that there are lots of nested function definitions, which are not supported by clang, so i want to use afl-gcc to generate CGs. 
But it turns out that afl-gcc doesn't support "-targets=$TMP_DIR/BBtargets.txt" and "-outdir=$TMP_DIR" options. it said "configure: error: C compiler cannot create executables"
is there any solutions? what compile options should be applied?
thx very much.

**Comment by strongcourage** [comment]
Hi. You can take a look into afl-as.h to see how AFL instruments the basic block ID. Then, the distance of each basic block to predefined targets could be instrumented in the same way. Note that you need to accumulate the total distance values and the number of exercised basic block at runtime in order to calculate the seed distance of the current input. AFLGo currently supports only llvm-mode. Best.
