### ISSUE TITLE
Reproducing 21409  CVE-2017-8392

### ISSUE THREAD

**Issue by scanakci** [aflgo/aflgo#76]
Hi,

I recently started using AFLGO. I successfully set up LLVM 4.0 and could actually fuzz libxml2 by following the steps in the repo. Next, I was trying to fuzz some programs for provided CVEs in the paper. Specifically, I gave a shot to [this bug](https://sourceware.org/bugzilla/show_bug.cgi?id=21409) which you listed in the paper.

Although compilation goes well (i.e. no error, objdump binary is generated with AFLGO's afl-clang), I get the following error when trying to generate distances:

"Couldn't find any binaries in folder /root/aflgo/experiments/objdump/binutils-gdb"

For a reason,  bc files are not generated during compilation. I am attaching the full script that will hopefully help you reproduce the error on your side on a Ubuntu 18.04 with llvm 4.0 installed. I also added the log file that contains all output when I run the attached script.  I will appreciate any guidance to help me identify the problem.

Thanks,

Sadullah

[log-script.zip](https://github.com/aflgo/aflgo/files/5397105/log-script.zip)

**Comment by strongcourage** [comment]
Hi Sadullah,

I've created a script to reproduce CVE-2017-8392 (based on our script of reproducing [CVE-2016-4487](https://github.com/aflgo/aflgo/blob/master/scripts/fuzz/cxxfilt-CVE-2016-4487.sh) of cxxfilt Binutils) as follows:
~~~
git clone git://sourceware.org/git/binutils-gdb.git CVE-2017-8392
cd CVE-2017-8392; git checkout a6c21d4a553de184562fd8409a5bcd3f2cc2561a
mkdir obj-aflgo; mkdir obj-aflgo/temp
export SUBJECT=$PWD; export TMP_DIR=$PWD/obj-aflgo/temp
export CC=$AFLGO/afl-clang-fast; export CXX=$AFLGO/afl-clang-fast++
export LDFLAGS=-lpthread
export ADDITIONAL="-targets=$TMP_DIR/BBtargets.txt -outdir=$TMP_DIR -flto -fuse-ld=gold -Wl,-plugin-opt=save-temps"
echo $'dwarf2.c:4212\nelf.c:8642\nobjdump.c:1486\nobjdump.c:1791\nobjdump.c:2304\nsection.c:1395\nobjdump.c:2438\nobjdump.c:3532\nobjdump.c:3589\nobjdump.c:3678\nobjdump.c:3699\nobjdump.c:4001\nlibc-start.c:287' > $TMP_DIR/BBtargets.txt
cd obj-aflgo; CFLAGS="-DFORTIFY_SOURCE=2 -fstack-protector-all -fno-omit-frame-pointer -g -Wno-error $ADDITIONAL" LDFLAGS="-ldl -lutil" ../configure --disable-shared --disable-gdb --disable-libdecnumber --disable-readline --disable-sim --disable-ld
make clean; make
cat $TMP_DIR/BBnames.txt | rev | cut -d: -f2- | rev | sort | uniq > $TMP_DIR/BBnames2.txt && mv $TMP_DIR/BBnames2.txt $TMP_DIR/BBnames.txt
cat $TMP_DIR/BBcalls.txt | sort | uniq > $TMP_DIR/BBcalls2.txt && mv $TMP_DIR/BBcalls2.txt $TMP_DIR/BBcalls.txt
cd binutils; $AFLGO/scripts/genDistance.sh $SUBJECT $TMP_DIR objdump -SD @@
cd ../../; mkdir obj-dist; cd obj-dist; # work around because cannot run make distclean
CFLAGS="-DFORTIFY_SOURCE=2 -fstack-protector-all -fno-omit-frame-pointer -g -Wno-error -distance=$TMP_DIR/distance.cfg.txt" LDFLAGS="-ldl -lutil" ../configure --disable-shared --disable-gdb --disable-libdecnumber --disable-readline --disable-sim --disable-ld
make
mkdir in; echo "" > in/in
$AFLGO/afl-fuzz -m none -z exp -c 45m -i in -o out binutils/objdump -SD @@
~~~
I run it and obtained the distance files after 1 hour. Note that I use Ubuntu 16.04 and LLVM 4.0, so hopefully you can run this script on your side.

Best. MD

**Comment by scanakci** [comment]
Hi @strongcourage 

Thank you for your quick reply. I will try it sometimes today and let you know if I can generate on my side.

**Comment by scanakci** [comment]
Hi @strongcourage,

I tried your script and successfully obtained the distance files. I could also start the fuzzing the objdump without any issue.

I have one follow-up question, though. How did you obtain the targets? In your script, it is manually specified but that would be good to know the commits that result in these targets. I tried to find the commit that introduced this bug but it was not really succesful since the bug looks like to exist for at least 8 years.

**Comment by strongcourage** [comment]
Glad to hear that. In this case, you would like to reproduce the bug that has been reported (by me) [here](https://sourceware.org/bugzilla/show_bug.cgi?id=21409). Basically, you can manually extract the targets from the bug report of ASAN or write a simple script to do so. In other application like fuzzing recent code changes, there is a solution to automatically generate `BBtargets.txt` as discussed in the libxml2 example.
Best. MD

**Comment by scanakci** [comment]
Thank you for the suggestion. You can close the issue now given that I could fuzz the objdump using your script.

**Comment by strongcourage** [comment]
I try to add more fuzzing scripts to reproduce the bugs used in our evaluation [here](https://github.com/aflgo/aflgo/tree/master/scripts/fuzz). Please feel free to make pull requests. Thanks.
