### ISSUE TITLE
why it returns two function names in Ftargets.txt

### ISSUE THREAD

**Issue by xiaosatianyu** [aflgo/aflgo#8]
Hi.
I set just one target in the BBtargets.txt, such as cdf.c:203, why it will return two Function names in Ftargets.txt, such as cdf_unpack_header and cdf_read_header. 

From the backtrace,  cdf_read_header calls cdf_unpack_header, and program crashes in the cdf_unpack_header function.
cdf.c:203 is the crash line in the cdf_unpack_header function.
thankyou

**Comment by thuanpv** [comment]
Hi.
AFLGo directs the search towards the line(s) of code that is specified in BBtargets.txt by prioritizing the paths leading to them. To do this, AFLGo instruments the basic blocks from which the program can reach the target line(s) of code. The instrumentation encodes the distance information so that its simulated annealing based power scheduler can decide which "path" to priotize. In your example, since the call sequence is cdf_read_header ==> cdf_unpack_header ==> target line of code so some basic blocks in these two functions should be instrumented and it is the reason why you see their names in Ftargets.txt. Hopefully, my answer helps. Please read our CCS'17 paper for more information.
Thuan
