### ISSUE TITLE
cooling_schedule

### ISSUE THREAD

**Issue by jintong0930** [aflgo/aflgo#86]
Hello, I want to ask a question that in cooling schedule, in AFLGo there are 4 measures(EXP, LOG, LIN, QUAD), but in AFLFast, there are only 3 measures(EXP, LIN, QUAD) in paper, so what means about SAN_LOG? Is this bring up by AFLGo?

**Comment by mboehme** [comment]
Hi @jintong0930, Thanks for reaching out! The search objectives and heuristics are quite different in AFLFast and AFLGo. You can read more about the corresponding power schedules in these papers:
* AFLFast: https://mboehme.github.io/paper/CCS16.pdf
* AFLGO: https://mboehme.github.io/paper/CCS17.pdf

(Closing this, since this is not an issue. You are welcome to comment if you have further questions).

**Comment by jintong0930** [comment]
So did you create this method of EXP, LOG, LIN and QUAD?

**Comment by mboehme** [comment]
Yes, we created these heuristics.

**Comment by jintong0930** [comment]
Ok, thank you.In the power schedule, the transition from exploration to exploitation is part of the simulated annealing algorithm, why I can’t find it in the code. It is in the article: "We let the cooling schedule enter exploitation when Tk ≤ 0.05. Adjustment for values other than 0.05 and for different cooling schedules is straightforward."

**Comment by mboehme** [comment]
You can have a look at our implementation of the annealing schedule here: https://github.com/aflgo/aflgo/blob/master/afl-fuzz.c#L4815 We are essentially translating the user-defined time to "switch" and Tk=0.05 into those constants that you see.

**Comment by jintong0930** [comment]
Is the function of this cooling schedule to enter the exploitation, that is, to call this when the temperature is less than 0.05?
